resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/release-service/config/default?ref=e855e4dd7dcbd4bd6f3376884b04bc0e60e4093a
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/release-service
  newName: quay.io/redhat-appstudio/release-service
  newTag: e855e4dd7dcbd4bd6f3376884b04bc0e60e4093a

namespace: release-service

patches:
  - ./manager_resources_patch.yaml
