name: Close PRs and delete branches daily

on:
  schedule:
    - cron: '25 8 * * *' 

jobs:
  close_and_delete_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
      with:
        gh-cli-version: 2.32.0

    - name: Close all open pull requests and delete branches
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      run: |
        gh auth login --with-token <<< "${{ secrets.TEST_TOKEN }}"
        PRs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')
        while read -r pr branch; do
          gh pr close $pr
          if [[ $branch != "main" && $branch != "master" ]]; then
            git push origin --delete $branch
          fi
        done <<< "$PRs"
